[build]
  base = "root-app"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  VITE_ENTRY_HEADER_APP_URL = "https://mf-header-poc.netlify.app/assets/remoteEntry.js"
  VITE_ENTRY_LOGIN_APP_URL = "https://mf-login.netlify.app/assets/remoteEntry.js"
  VITE_ENTRY_HERO_APP_URL = "https://mf-hero-app.netlify.app/assets/remoteEntry.js"
  VITE_ENTRY_ABOUT_APP_URL = "https://mf-about-app.netlify.app/assets/remoteEntry.js"
